# ----------------------------------------------------- 
# Environments
# -----------------------------------------------------

# Pavucontrol floating
windowrulev2 = float,class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = size 700 600,class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = center,class:(.*org.pulseaudio.pavucontrol.*)
windowrulev2 = pin,class:(.*org.pulseaudio.pavucontrol.*)

# Tor Browser
windowrulev2 = float, initialtitle:^(Tor Browser)$
windowrulev2 = size 1200 600,initialtitle:^(Tor Browser)$
windowrulev2 = center, initialtitle:^(Tor Browser)$

#Virt-manager
windowrulev2 = float, initialtitle:^(Virtual Machine Manager)$
windowrulev2 = size 800 600,initialtitle:^(Virtual Machine Manager)$
windowrulev2 = center, initialtitle:^(Virtual Machine Manager)$

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
